import Head from 'next/head';
import 'bootstrap/dist/css/bootstrap.css';

export default function Home() {
	return (
		<div>
			<Head>
				<title>Environews RDC</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
		</div>
	);
}
