#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo '####################################################################'
echo '#### Styling, testing and building your project before commiting ###'
echo '####################################################################'

# Check tsconfig standards
npm run check-types || 
(
    echo 'Failed Type check
          Are you seriously trying to write that ? Make the changes required above.'
          false;
)

# Check Prettier standards
npm run check-format || 
(
    echo 'Its F**KING RAW - Your styling looks disgusting.
          Prettier Chec Failed. Run npm run format, add changes and try commit again.'
          false;
)
# Check Eslint standards
npm run check-lint || 
(
    echo 'Get that weaks s**t out of here !
          Eslint Check Failed. Make the required changes listed above, add changes and try to commit again.'
          false;
)

#If everything passes .... try to run build
# echo '... Alright ... Code looks good to me ... Trying to build now'

# npm run build || 
# (
#     echo 'Better cal Eminence or Emmanuella ... Because your build failed
#           Next build failed : View the errors above to see why.'
#           false;
# )

#If it builds we can commit
echo 'You win this time ... I am committing this now.'
